export const LOGIN_ACTION = 'LOGIN_ACTION';
export const REQUEST_CURRENCIES = 'REQUEST_CURRENCIES';
export const RECEIVE_CURRENCIES_SUCCESS = 'RECEIVE_CURRENCIES_SUCCESS';
export const RECEIVE_CURRENCIES_FAILURE = 'REQUEST_CURRENCIES_FAILURE';
export const GET_EXPENSES_INFO = 'GET_EXPENSES_INFO';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
